### ISSUE TITLE
Toggle menu from link

### ISSUE THREAD

**Issue by geealbers** [gettypubs/inventionofphoto-deck.js#2]
http://gettypubs.github.io/inventionofphoto-deck.js/inventionofphoto-deckjs.html

I'd like to add a toggleMenu function to the "MENU" tag at the lower right. (http://imakewebthings.com/deck.js/docs/#deck-menu) Seems like it should be super simple but I'm not getting anywhere with it. I must be missing something in the syntax. Not important, but can you take a look when you have a chance?

And the Demo Site banner could probably be more elegant if you have any ideas (though I do want it sort of painfully obvious).

Thanks.

**Comment by egardner** [comment]
Closed this with a28284b.
